### ISSUE TITLE
RFC: Introduce fallback support for `BuildPropertiesPlugin`

### ISSUE THREAD

**Issue by mr-archano** [novoda/spikes#145]
### Scope

While trying to integrate the current version of `BuildPropertiesPlugin` in some internal project we realised that we should consider having support for fallback values, eg:

```groovy
String value = buildProperties.secrets['foo'].or(buildProperties.other['bar']).string
```

Ideally we could provide support also to closures and plain values, eg:

```groovy
Double value = buildProperties.config['rate'].or({ Math.random() }).double
```

or

```groovy
Double value = buildProperties.config['rate'].or(1.0).double
```

### Considerations/Implementation details

A simple implementation would introduce a `Entry.or(def other)` method, creating a new `Entry` where the `value` closure will be evaluated considering the provided fallback. E-Z.

Couple of considerations more:
- It would be nice to get access to project properties and system environment variables via a predefined set of entries in `buildProperties`. What if we had `buildProperties.project` and `buildProperties.env` to access them? eg:
```groovy
buildProperties.project['foo']
buildProperties.env['BAR_PATH']
```
- At the moment it's possible to override the value of a property [via command line](https://github.com/novoda/spikes/blob/master/BuildPropertiesPlugin/README.md#override-properties-at-build-time). What about removing this feature in favour of a more explicit support via `or()`? eg:
```groovy
buildProperties.project['foo'].or(buildProperties.secrets['foo'])
```
- When trying to access a property in a `Properties` file an [error is thrown](https://github.com/novoda/spikes/blob/master/BuildPropertiesPlugin/plugin/src/main/groovy/com/novoda/buildproperties/FilePropertiesEntries.groovy#L40-L49). We need to consider the error handling as part of the implementation of the `Entry.or()` to bubble up a meaningful error when the whole chain of fallbacks evaluates to `null`. An alternative would be to always fallback to `null` if a property is not available, any thoughts?

It would be great to collect some feedback and brainstorm possible solutions to the issues above.

**Comment by frapontillo** [comment]
Love the `or` spec idea.

My thoughts:
* `or` should ideally accept anything, from value to closure 👍.
* environment variables are okay, even though not a priority IMO.
* I wouldn't remove command line support, it might be very useful to specify different behaviours (e.g. CI).
* If a variable is not found I would still throw an exception, if we have a chance to specify `.or(SOME_DEFAULT_VALUE)` after the retrieval attempt. This makes default values explicit if not configured.

**Comment by mr-archano** [comment]
@frapontillo, thanks for your time. 
> or should ideally accept anything, from value to closure

Totally agree, hence the signature `Entry.or(def other)`. Cool thing is we could then also write `|` because Groovy operators 😸 

> environment variables are okay, even though not a priority IMO.

I agree, but it's a blocker for the integration in Pulse for instance. And I would really really like to complete that 💃 

> if a variable is not found I would still throw an exception, if we have a chance to specify .or(SOME_DEFAULT_VALUE) after the retrieval attempt. This makes default values explicit if not configured.

My idea was to use a `try`/`catch` in the implementation like below:
```groovy
Entry or(def fallback) {
        def other = from(fallback)
        new Entry(key, {
            try {
                return getValue() ?: other.call()
            } catch (Throwable e) {
                return other.call()
            }
        })
    }

    private static def from(def fallback) {
        if (fallback instanceof Entry) {
            return { (fallback as Entry).getValue() }
        }
        if (fallback instanceof Closure) {
            return fallback
        }
        return { fallback }
    }
``` 
The issue is the evaluation of `other.call()` might throw another exception, shadowing the one thrown by `getValue()`. Is that acceptable behaviour?

**Comment by ouchadam** [comment]
pretty much what @frapontillo said

having fast feedback when the values are completely missing would be great.

What's the priority ordering you would expect?

- buildProperties.config['rate']
- buildProperties.config['rate'].or
- env
- command line

**Comment by frapontillo** [comment]
I have no idea how Pulse works, but can't you launch parametrised builds? If so, just pass a command line argument with the expanded environment variable and you're done.

======

I don't think we have that issue. By postponing the resolution of the property to the moment  we do `.double`/`.string` etc we execute closures only in the end.

======

@ouchadam I don't think there is a resolution order: those properties are set on different scopes. If you want to order it yourself you could do
```groovy
buildProperties.project['foo']
    .or(buildProperties.args['some_command_line_arg'])
    .or(buildProperties.env['MY_SYSTEM_WIDE_DEFAULT'])
```

**Comment by mr-archano** [comment]
@ouchadam I'm more considering to provide no bulit-in priority at all, promoting explicitness instead, eg:
```groovy
buildProperties.env['FOO'] | buildProperties.project['bar'] | 'defaultValue'
```
this way we can taylor the evaluation chain according to the specific case.

**Comment by mr-archano** [comment]
@frapontillo I'd like not to change the CI setup at all (especially the one client-side). Having a simple drop-in replacement would be great.
RE the error handling you're right, but I was more considering we'll have different contexts, and possibly different keys in the chain. Eg:
```groovy
buildProperties.env['KEY_1']
  .or(buildProperties.project['key2'])
  .or(buildProperties.secrets['key3'])
```
This will make difficult to provide a meaningful error message taking in account all the (failed) fallbacks. Reading `No 'key3' provided in properties 'secrets'` could be a little bit confusing to the user, right?

**Comment by tasomaniac** [comment]
I've been planning to use the plugin in GDG Frisbee project. This was kinda blocker for me. Because if property values are not available, we put fake ones that works for development. 

I really like the idea and how you are planning to use `.or`.

About the error, I wouldn't care that much. Do whatever looks better or easier. Maybe don't catch any exception at all. Don't provide `key2` when exception occurs in `key1`. Only provide it when it is not available.

**Comment by frapontillo** [comment]
@mr-archano not necessarily, we could collect the exceptions and throw them at once in a `CompositeException` or something like that.

**Comment by xrigau** [comment]
@mr-archano great idea 👍 

Re: error handling perhaps the thing needed is something like `orNull`, then you could just return null if the property doesn't exist instead of throwing and you could use that method inside the `or`  to avoid nested `try-catch`es, thoughts?

**Comment by blundell** [comment]
> An alternative would be to always fallback to null if a property is not available, any thoughts?

yeah you might want to make some properties force a value or you get an exception? could null be misconstrued as `"null"` should it be `""`?

**Comment by mr-archano** [comment]
Awesome feedback guys 👏, thanks a lot.
I think the natural next step is to spend some time trying to implement the feature. I will issue a PR asap.

**Comment by mr-archano** [comment]
Version `1.1.0` of the plugin ships both [fallback values](#150) and [environment variables](#151) support. We can close this.
