### ISSUE TITLE
DropCap/Allow hyperlinks in the DropCap content

### ISSUE THREAD

**Issue by gpavankumar1974** [novoda/spikes#283]
I have gone through a sample
https://github.com/novoda/spikes/tree/master/drop-cap

Can you please let me know how can i give hyperlink to a specified text in dropcapview.

It would be helpful if you can respond ASAP.

**Comment by Mecharyry** [comment]
Hi @gpavankumar1974, unfortunately, `DropCap` doesn't support hyperlinks in the main body of the `DropCap` content at the moment. This could be a feature in future or alternatively, you are very welcome to open a PR against this library 😃

**Comment by lgvalle** [comment]
Is this still a desired feature?

**Comment by Mecharyry** [comment]
It is 😄  I'm just not sure when I will have time to work on it 😢

**Comment by Mecharyry** [comment]
Moved to the `DropCap` repo -> https://github.com/novoda/drop-cap/issues/1
