### ISSUE TITLE
Cannot import to project

### ISSUE THREAD

**Issue by Rehckover** [novoda/spikes#297]
When trying to sync project with compile 'com.novoda:drop-cap:1.1.0' this error occured. What's wrong?

> Error:(32, 13) Failed to resolve: com.novoda:drop-cap:1.1.0

**Comment by Mecharyry** [comment]
Hi @Rehckover I'll take a look into this for you ASAP.

**Comment by Mecharyry** [comment]
Hi @Rehckover, sorry for the delay. There was an error with the Readme, this project has not been promoted via JCenter yet but uses directly maven.

If you replace the following: 
```
    repositories {
        jcenter()
    }
```

with
```
    repositories {
        maven {
            url 'https://dl.bintray.com/novoda/maven'
        }
    }
```

it should work 😄  

Sorry again for the trouble you had importing the library.

**Comment by Mecharyry** [comment]
This issue has been resolved with the release to Jcenter.
