### ISSUE TITLE
eNews first item misaligned

### ISSUE THREAD

**Issue by blundell** [novoda/spikes#327]
This is because an ID is set on each item, but because the ID is not unique it is only applied to the first item.

https://github.com/novoda/spikes/blob/master/enews/enews-java/html-generator/src/main/java/com/novoda/enews/HtmlGenerator.java#L191

![screen shot 2017-11-13 at 08 21 47](https://user-images.githubusercontent.com/655860/32715820-ad8a10e2-c84b-11e7-933f-793c1b73b368.png)

**Comment by caroinberlin** [comment]
![screen shot 2017-11-14 at 2 27 22 pm](https://user-images.githubusercontent.com/13833681/32783041-b20b58ba-c94a-11e7-9802-0737a210d44c.png)
