### ISSUE TITLE
eNews smaller images

### ISSUE THREAD

**Issue by Mecharyry** [novoda/spikes#328]
### Problem
Images in the newsletter are a little on the large side and are a detriment to the reading flow of the newsletter. 

### Solution 
We should take inspiration from some other newsletters:
https://www.launchticker.com/
https://www.launchticker.com/
https://inside.com/campaigns/inside-ai-2017-11-12-3973

**Comment by caroinberlin** [comment]
I attached the original design for the article photos - I think it might be less distracting to handle images if we centered them like so? Currently there is a crazy indent in the first image, and the text in the intro paragraph is a little bit light in contrast to the articles. 


![screen shot 2017-11-14 at 2 27 22 pm](https://user-images.githubusercontent.com/13833681/32782368-75acfe0c-c948-11e7-9e48-728f3e8301b6.png)

**Comment by caroinberlin** [comment]
![large desktop](https://user-images.githubusercontent.com/13833681/32782962-6eb37d54-c94a-11e7-8b0f-8ef18d978f84.png)
Also here is an alternate design for smaller images!

**Comment by lgvalle** [comment]
What's the status of this @Mecharyry @caroinberlin  ?

**Comment by Mecharyry** [comment]
Sorry @lgvalle I have no idea what is happening with this task. @caroinberlin ?

**Comment by caroinberlin** [comment]
Problem fixed with mailchimp template - images are fine without this refinement
